service: calendar-api
frameworkVersion: "2 || 3"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-west-2:291892767258:table/ScheduleTable

functions:
  hello:
    handler: src/hello.hello
    events:
      - httpApi:
          path: /
          method: get

  addScheduleItem:
    handler: src/addScheduleItem.addScheduleItem
    events:
      - httpApi:
          path: /schedule
          method: post

  getScheduleItems:
    handler: src/getScheduleItems.getScheduleItems
    events:
      - httpApi:
          path: /schedule
          method: get

  updateScheduleItem:
    handler: src/updateScheduleItem.updateScheduleItem
    events:
      - httpApi:
          path: /schedule
          method: put

  deleteScheduleItem:
    handler: src/deleteScheduleItem.deleteScheduleItem
    events:
      - httpApi:
          path: /schedule
          method: delete

resources:
  Resources:
    ScheduleTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ScheduleTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
